# MongoDB Atlas connection string (replace <username> and <password>)
spring.data.mongodb.uri=mongodb+srv://jiyavinchhi123:Jiyavinchhi123@cluster0.rqlhqfe.mongodb.net/formDB?retryWrites=true&w=majority

# Optional: show simple server info
server.port=8080
